fun fn() {
    fun e() {
        throw 123
    }
    e()
}

try {
    fn()
} catch val {
    assert(val.value() == 123)
}